from conftest import ingest_fixtures, parse_sse, signup


def _chat(client, message, conversation_id=None):
    r = client.post("/api/chat", json={"message": message,
                                       "conversation_id": conversation_id})
    assert r.status_code == 200, r.text
    return parse_sse(r.text)


def test_grounded_answer_with_citation(client):
    """Acceptance §13: grounded answer with at least one working source link,
    and the conversation survives logout/login."""
    ingest_fixtures(client)
    signup(client)

    events = _chat(client, "What skills do I need to become a data analyst?")
    sources = next(e for e in events if e["type"] == "sources")["sources"]
    assert sources, "expected at least one cited source"
    assert all(s["source_url"] for s in sources)

    answer = "".join(e["text"] for e in events if e["type"] == "token")
    assert "fixture://" in answer  # citation link embedded in the reply
    done = next(e for e in events if e["type"] == "done")
    assert done["conversation_id"]

    # log out, log back in, conversation still there with both messages
    client.post("/api/auth/logout")
    client.post("/api/auth/login", json={"email": "user@example.com",
                                         "password": "password123"})
    convs = client.get("/api/conversations").json()
    assert len(convs) == 1
    msgs = client.get(f"/api/conversations/{convs[0]['id']}/messages").json()
    assert [m["role"] for m in msgs] == ["user", "assistant"]


def test_out_of_scope_polite_redirect(client):
    """Acceptance §13: out-of-scope question yields a redirect, not a
    hallucinated answer."""
    ingest_fixtures(client)
    signup(client)
    events = _chat(client, "Who won the football world cup final?")
    answer = "".join(e["text"] for e in events if e["type"] == "token")
    assert "jobs, skills, careers, and training" in answer
    assert "fixture://" not in answer  # no fabricated citation
    sources = next(e for e in events if e["type"] == "sources")["sources"]
    assert sources == []


def test_conversation_title_autogenerated(client):
    ingest_fixtures(client)
    signup(client)
    events = _chat(client, "What skills do I need to become a data analyst?")
    done = next(e for e in events if e["type"] == "done")
    assert "data analyst" in done["title"].lower()


def test_users_cannot_read_others_conversations(client):
    ingest_fixtures(client)
    signup(client, email="alice@example.com")
    events = _chat(client, "skills for software developer?")
    conv_id = next(e for e in events if e["type"] == "done")["conversation_id"]

    client.post("/api/auth/logout")
    signup(client, email="bob@example.com")
    assert client.get(f"/api/conversations/{conv_id}/messages").status_code == 404
